Counted = Int

Emitted = String

HexByte = String

InToken = Bool

IsSpace = Bool

Nibble = Int

Int => Emitted {
    Int
        -> Quotient(16)
        -> Nibble
        -> HexByte
        -> Joined(Int -> Remainder(16) -> Nibble -> HexByte)
}

Nibble => HexByte {
    "0123456789abcdef" -> Substring(Nibble -> Sum(1) -> From * Nibble -> Sum(1) -> To)
}

Pos = Int

Scanned = Int

Int => IsSpace {
    Int -> Eq(32) -> (
        * False {
            Int -> Eq(10) -> (
                * False { Int -> Eq(9) }
                * True { True() }
            )
        }
        * True { True() }
    )
}

Source = String

Counted * InToken * Pos * Source => Scanned {
    Pos -> Gt(Source -> Length) -> (
        * False {
            Source -> ByteAt(Pos) -> IsSpace -> (
                * False {
                    InToken -> (
                        * False {
                            Counted
                                -> Sum(1)
                                -> Counted
                                -> Scanned(True() -> InToken * Pos -> Sum(1) -> Pos * Source)
                        }
                        * True {
                            Counted -> Scanned(True() -> InToken * Pos -> Sum(1) -> Pos * Source)
                        }
                    )
                }
                * True { Counted -> Scanned(False() -> InToken * Pos -> Sum(1) -> Pos * Source) }
            )
        }
        * True { Counted }
    )
}

Unit => Program {
    `0061736d010000000105016000017f03020100070a0106616e7377657200000a0601040041{
        Counted(0)
            -> Scanned(False() -> InToken * Pos(1) * Source("Bool = False + True"))
            -> Emitted
    }0b`
        -> Print
}
