//! Bundles the shipped packages under `packages/<namespace>/<package>/` into
//! the compiler binary as a flat registry the loader can consult at runtime.
//!
//! Today the only shipped package is `canon/std`, which contains both the
//! hand-written wrappers under `src/` and the WIT-derived bindings under
//! `bindgen/` (committed so `cargo build` works on a fresh clone without a
//! prior `canon install` step). Both directories flatten into the same
//! `BundledFile` namespace.
//!
//! The output is a generated Rust file (`bundled_packages.rs`) included by
//! `src/loader.rs`. It contains a single `&[BundledPackage]` slice; each
//! entry lists the package's manifest source plus every `.can` file under its
//! roots, with `include_str!` references so the contents live in the binary.
//!
//! Walking the filesystem at build time means: drop a file into
//! `packages/canon/std/` (or add a new package directory) and the next
//! `cargo build` picks it up automatically. There is no hand-maintained
//! `STDLIB`-style array.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let packages_root = Path::new(&manifest_dir).join("packages");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let out_path = Path::new(&out_dir).join("bundled_packages.rs");

    // Re-run if anything under `packages/` changes — Cargo doesn't recurse
    // by default, so we have to enumerate every file we depend on.
    println!("cargo:rerun-if-changed=packages");
    println!("cargo:rerun-if-changed=build.rs");

    let mut packages = discover_packages(&packages_root);
    // Deterministic output: bundle order matches alphabetical package name,
    // and files within a package are alphabetical by path. This keeps the
    // generated Rust diff-stable across rebuilds.
    packages.sort_by(|a, b| a.name.cmp(&b.name));

    let mut code = String::new();
    code.push_str("// Generated by build.rs from `packages/`. Do not edit.\n\n");
    code.push_str("pub(crate) const BUNDLED_PACKAGES: &[BundledPackage] = &[\n");
    for pkg in &packages {
        code.push_str("    BundledPackage {\n");
        code.push_str(&format!("        name: {:?},\n", pkg.name));
        code.push_str(&format!(
            "        manifest_src: include_str!({:?}),\n",
            pkg.manifest_path.to_string_lossy()
        ));
        code.push_str("        files: &[\n");
        for file in &pkg.files {
            code.push_str("            BundledFile {\n");
            code.push_str(&format!("                path: {:?},\n", file.rel_path));
            code.push_str(&format!(
                "                source: include_str!({:?}),\n",
                file.abs_path.to_string_lossy()
            ));
            // Build-time absolute path. Used by the LSP for go-to-definition
            // when running against a source tree; for an installed binary
            // these paths won't exist, which is the same caveat the previous
            // `concat!(env!("CARGO_MANIFEST_DIR"), "/std")` constant had.
            code.push_str(&format!(
                "                abs_path: {:?},\n",
                file.abs_path.to_string_lossy()
            ));
            match &file.wit_urn {
                Some(urn) => code.push_str(&format!("                wit_urn: Some({:?}),\n", urn)),
                None => code.push_str("                wit_urn: None,\n"),
            }
            code.push_str("            },\n");
            println!("cargo:rerun-if-changed={}", file.abs_path.display());
        }
        code.push_str("        ],\n");
        code.push_str("    },\n");
        println!("cargo:rerun-if-changed={}", pkg.manifest_path.display());
    }
    code.push_str("];\n");

    fs::write(&out_path, code).expect("failed to write bundled_packages.rs");
}

#[derive(Debug)]
struct DiscoveredPackage {
    /// Canonical package name as declared on disk: `<namespace>/<package>`.
    /// We don't parse the manifest here — the runtime parser is authoritative
    /// — but we trust the directory layout to give us the right name. If a
    /// manifest disagrees, the loader will complain at startup.
    name: String,
    manifest_path: PathBuf,
    files: Vec<DiscoveredFile>,
}

#[derive(Debug)]
struct DiscoveredFile {
    /// Path relative to the package root, e.g. `clocks/monotonic_clock.can`.
    /// Always uses `/` separators so it matches the `use` path users write.
    rel_path: String,
    abs_path: PathBuf,
    /// WIT interface URN of the form `"<ns>:<pkg>/<iface>@<version>"`,
    /// or `None` for hand-written files under `src/`. Populated for
    /// `bindgen/` files by consulting the package's
    /// `bindgen/_install.toml`. The loader uses this to fill in the
    /// path string of bare `extern Wasm` declarations at parse time.
    wit_urn: Option<String>,
}

fn discover_packages(root: &Path) -> Vec<DiscoveredPackage> {
    let mut out = Vec::new();
    if !root.exists() {
        return out;
    }
    // Layout: packages/<namespace>/<package>/canon.toml + sources.
    for namespace_entry in fs::read_dir(root).expect("read packages dir").flatten() {
        let namespace_path = namespace_entry.path();
        if !namespace_path.is_dir() {
            continue;
        }
        let namespace = namespace_path
            .file_name()
            .and_then(|s| s.to_str())
            .expect("namespace name is utf-8")
            .to_string();
        for package_entry in fs::read_dir(&namespace_path)
            .expect("read namespace dir")
            .flatten()
        {
            let package_path = package_entry.path();
            if !package_path.is_dir() {
                continue;
            }
            let package = package_path
                .file_name()
                .and_then(|s| s.to_str())
                .expect("package name is utf-8")
                .to_string();
            let manifest_path = package_path.join("canon.toml");
            assert!(
                manifest_path.exists(),
                "package directory `{}` has no `canon.toml`",
                package_path.display()
            );
            // Sources live under `<package>/src/`. Keeping the manifest at the
            // package root (alongside `src/`) makes the metadata immediately
            // visible when scanning the directory — same shape as Cargo's
            // `Cargo.toml` + `src/`. The `path` we record on each
            // `BundledFile` is relative to `src/`, not to the package root,
            // so `use canon/std/Body` continues to map to `body.can`.
            let src_root = package_path.join("src");
            let mut files = Vec::new();
            if src_root.exists() {
                collect_ow_files(&src_root, &src_root, &mut files);
            }
            // Bindings generated by `canon install` live under
            // `<package>/bindgen/`. They share the same flat namespace as
            // `src/` from the bundle's perspective — a file at
            // `<package>/bindgen/wasi/random/random.can` is bundled with
            // `rel_path = "wasi/random/random.can"`, the same form a
            // hand-written file at `<package>/src/wasi/random/random.can`
            // would have. This is what lets `canon/std`'s own source
            // do `use wasi/random/random` and have it resolve via the
            // same-package fallback in `process_bundled_use`.
            let bindgen_root = package_path.join("bindgen");
            if bindgen_root.exists() {
                collect_ow_files(&bindgen_root, &bindgen_root, &mut files);
            }
            // Read the install index from the bindgen directory (if it
            // exists) and attach the URN to each `bindgen/` file. The
            // installer's filename constant lives in `src/install.rs`;
            // we hardcode it here because `build.rs` can't depend on
            // the crate it's about to build.
            if bindgen_root.exists() {
                let index_path = bindgen_root.join("_install.toml");
                if index_path.is_file() {
                    let urns =
                        parse_install_index(&fs::read_to_string(&index_path).unwrap_or_else(|e| {
                            panic!("could not read `{}`: {e}", index_path.display())
                        }));
                    for f in files.iter_mut() {
                        if let Some(urn) = urns.get(&f.rel_path) {
                            f.wit_urn = Some(urn.clone());
                        }
                    }
                }
            }

            // Reject collisions explicitly. If two files exist with the
            // same `rel_path` (one in `src/`, one in `bindgen/`), the
            // bundled lookup would be ambiguous; surface the conflict
            // here rather than letting it produce silently wrong behavior.
            files.sort_by(|a, b| a.rel_path.cmp(&b.rel_path));
            for win in files.windows(2) {
                assert!(
                    win[0].rel_path != win[1].rel_path,
                    "package `{}/{}`: file `{}` exists in both `src/` and `bindgen/`; rename one to disambiguate",
                    namespace,
                    package,
                    win[0].rel_path
                );
            }
            // Track the index file too so cargo reruns the build when it
            // changes. The index isn't bundled itself — it's been read
            // into individual `BundledFile.wit_urn` values above — but
            // its content steers the generated registry.
            if bindgen_root.exists() {
                let index_path = bindgen_root.join("_install.toml");
                if index_path.is_file() {
                    println!("cargo:rerun-if-changed={}", index_path.display());
                }
            }

            out.push(DiscoveredPackage {
                name: format!("{namespace}/{package}"),
                manifest_path,
                files,
            });
        }
    }
    out
}

fn collect_ow_files(root: &Path, dir: &Path, out: &mut Vec<DiscoveredFile>) {
    for entry in fs::read_dir(dir).expect("read package dir").flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_ow_files(root, &path, out);
        } else if path.extension().and_then(|s| s.to_str()) == Some("can") {
            let rel = path
                .strip_prefix(root)
                .expect("file under root")
                .to_string_lossy()
                .replace('\\', "/");
            out.push(DiscoveredFile {
                rel_path: rel,
                abs_path: path,
                wit_urn: None,
            });
        }
    }
}

/// Minimal `_install.toml` parser used at build time. Mirrors the
/// runtime parser in `src/install.rs::parse_install_index` but lives
/// here because `build.rs` can't import from the crate it's about to
/// build. Format is a strict subset of TOML: comment lines starting
/// with `#`, blank lines, and `"key" = "value"` pairs.
fn parse_install_index(source: &str) -> std::collections::HashMap<String, String> {
    let mut out = std::collections::HashMap::new();
    for (idx, raw) in source.lines().enumerate() {
        let line_no = idx + 1;
        let line = raw.split('#').next().unwrap_or("").trim();
        if line.is_empty() {
            continue;
        }
        let eq = line.find('=').unwrap_or_else(|| {
            panic!("_install.toml:{line_no}: expected `key = value`, got `{line}`")
        });
        let key = unquote_install_index(line[..eq].trim(), line_no);
        let value = unquote_install_index(line[eq + 1..].trim(), line_no);
        out.insert(key, value);
    }
    out
}

fn unquote_install_index(raw: &str, line_no: usize) -> String {
    assert!(
        raw.len() >= 2 && raw.starts_with('"') && raw.ends_with('"'),
        "_install.toml:{line_no}: expected quoted string, got `{raw}`"
    );
    raw[1..raw.len() - 1].to_string()
}
