//! Bundles the shipped packages under `packages/<namespace>/<package>/` into
//! the compiler binary as a flat registry the loader can consult at runtime.
//!
//! `canon` — the prelude, at `packages/canon/` — contains both the
//! hand-written wrappers under `src/` and the WIT-derived bindings under
//! `bindgen/` (committed so `cargo build` works on a fresh clone without a
//! prior `canon install` step). Both directories flatten into the same
//! `BundledFile` namespace. The packages beside it (`packages/canon/<name>/`,
//! bundled as `canon/<name>`) ship in the binary too, but only reach a
//! program once `canon add` vendors them into its `deps/`.
//!
//! The output is a generated Rust file (`bundled_packages.rs`) included by
//! `src/loader.rs`. It contains a single `&[BundledPackage]` slice; each
//! entry lists every `.can` file under the package's roots, with
//! `include_str!` references so the contents live in the binary.
//!
//! Walking the filesystem at build time means: drop a file into
//! `packages/canon/` (or add a new package directory) and the next
//! `cargo build` picks it up automatically. There is no hand-maintained
//! `STDLIB`-style array.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let packages_root = Path::new(&manifest_dir).join("packages");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let out_path = Path::new(&out_dir).join("bundled_packages.rs");

    // Re-run if anything under `packages/` changes — Cargo doesn't recurse
    // by default, so we have to enumerate every file we depend on.
    println!("cargo:rerun-if-changed=packages");
    println!("cargo:rerun-if-changed=build.rs");

    let mut packages = discover_packages(&packages_root);
    // Deterministic output: bundle order matches alphabetical package name,
    // and files within a package are alphabetical by path. This keeps the
    // generated Rust diff-stable across rebuilds.
    packages.sort_by(|a, b| a.name.cmp(&b.name));

    let mut code = String::new();
    code.push_str("// Generated by build.rs from `packages/`. Do not edit.\n\n");
    code.push_str("pub(crate) const BUNDLED_PACKAGES: &[BundledPackage] = &[\n");
    for pkg in &packages {
        code.push_str("    BundledPackage {\n");
        code.push_str(&format!("        name: {:?},\n", pkg.name));
        code.push_str("        files: &[\n");
        for file in &pkg.files {
            code.push_str("            BundledFile {\n");
            code.push_str(&format!("                path: {:?},\n", file.rel_path));
            code.push_str(&format!(
                "                source: include_str!({:?}),\n",
                file.abs_path.to_string_lossy()
            ));
            // Build-time absolute path. Used by the LSP for go-to-definition
            // when running against a source tree; for an installed binary
            // these paths won't exist, which is the same caveat the previous
            // `concat!(env!("CARGO_MANIFEST_DIR"), "/std")` constant had.
            code.push_str(&format!(
                "                abs_path: {:?},\n",
                file.abs_path.to_string_lossy()
            ));
            code.push_str("            },\n");
            println!("cargo:rerun-if-changed={}", file.abs_path.display());
        }
        code.push_str("        ],\n");
        code.push_str("    },\n");
    }
    code.push_str("];\n");

    fs::write(&out_path, code).expect("failed to write bundled_packages.rs");
}

#[derive(Debug)]
struct DiscoveredPackage {
    /// Canonical package name as declared on disk: `<namespace>/<package>`.
    /// The directory layout is the single source of the name.
    name: String,
    files: Vec<DiscoveredFile>,
}

#[derive(Debug)]
struct DiscoveredFile {
    /// Path relative to the package root, e.g. `clocks/monotonic_clock.can`.
    /// Always uses `/` separators so it matches the `use` path users write.
    rel_path: String,
    abs_path: PathBuf,
}

fn discover_packages(root: &Path) -> Vec<DiscoveredPackage> {
    let mut out = Vec::new();
    if root.exists() {
        walk_packages(root, root, &mut out);
    }
    out
}

/// A directory carrying its own `src/` *is* a package, named by its path
/// under `packages/` — `packages/canon/` is `canon` (the prelude) and
/// `packages/canon/markdown/` is `canon/markdown` — the same structural
/// detection the language applies everywhere else. Every other
/// subdirectory is walked for more packages, except a package's own trees
/// (`src/`, `bindgen/`, `wit/`, `build/`).
fn walk_packages(root: &Path, dir: &Path, out: &mut Vec<DiscoveredPackage>) {
    if dir != root && dir.join("src").is_dir() {
        let name = dir
            .strip_prefix(root)
            .expect("package under root")
            .to_string_lossy()
            .replace('\\', "/");
        if let Some(pkg) = discover_package(dir, name) {
            out.push(pkg);
        }
    }
    for entry in fs::read_dir(dir).expect("read packages dir").flatten() {
        let path = entry.path();
        if !path.is_dir() {
            continue;
        }
        let name = entry.file_name();
        let name = name.to_string_lossy();
        if name.starts_with('.') || ["src", "bindgen", "wit", "build"].contains(&name.as_ref()) {
            continue;
        }
        walk_packages(root, &path, out);
    }
}

fn discover_package(package_path: &Path, name: String) -> Option<DiscoveredPackage> {
    // Sources live under `<package>/src/`. The `path` we record on
    // each `BundledFile` is relative to `src/`, not to the package
    // root, so `use canon/Body` maps to `body.can`.
    let src_root = package_path.join("src");
    let mut files = Vec::new();
    if src_root.exists() {
        collect_ow_files(&src_root, &src_root, &mut files);
    }
    // Bindings generated by `canon install` live under
    // `<package>/bindgen/`. They share the same flat namespace as
    // `src/` from the bundle's perspective — a file at
    // `<package>/bindgen/wasi/random/random.can` is bundled with
    // `rel_path = "wasi/random/random.can"`, the same form a
    // hand-written file at `<package>/src/wasi/random/random.can`
    // would have. This is what lets the stdlib's own source
    // do `use wasi/random/random` and have it resolve via the
    // same-package fallback in `process_bundled_use`.
    let bindgen_root = package_path.join("bindgen");
    if bindgen_root.exists() {
        collect_ow_files(&bindgen_root, &bindgen_root, &mut files);
    }
    // Collision rule: a hand-written file under `src/` shadows
    // the generated file at the same `rel_path` under
    // `bindgen/`. This is how the stdlib supersedes a machine
    // surface it needs to hand-maintain for now — e.g.
    // `wasi/http@<ver>/types.can`, whose resource-method
    // bindings the bindgen can't emit until resource lowering
    // lands. `src/` files were collected first, so keeping the
    // first occurrence keeps the hand-written one.
    let mut seen_rel: std::collections::HashSet<String> = std::collections::HashSet::new();
    files.retain(|f| seen_rel.insert(f.rel_path.clone()));
    files.sort_by(|a, b| a.rel_path.cmp(&b.rel_path));
    if files.is_empty() {
        return None;
    }
    Some(DiscoveredPackage { name, files })
}

fn collect_ow_files(root: &Path, dir: &Path, out: &mut Vec<DiscoveredFile>) {
    for entry in fs::read_dir(dir).expect("read package dir").flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_ow_files(root, &path, out);
        } else if path.extension().and_then(|s| s.to_str()) == Some("can") {
            // A package's tests (`*_test.can`) are its examples, not its
            // surface: `canon doc` reads them, `canon add` does not copy
            // them.
            if path
                .file_name()
                .and_then(|s| s.to_str())
                .is_some_and(|s| s.ends_with("_test.can"))
            {
                continue;
            }
            let rel = path
                .strip_prefix(root)
                .expect("file under root")
                .to_string_lossy()
                .replace('\\', "/");
            out.push(DiscoveredFile {
                rel_path: rel,
                abs_path: path,
            });
        }
    }
}
