IndexBody = Body

NotFound = Body

NoteOne = Body

NoteTwo = Body

Unit => IndexBody {
    [{"id":1,"title":"ship canon v1"},{"id":2,"title":"write the docs"}] -> Body
}

Unit => NotFound {
    {"error":"not found"} -> Body
}

Unit => NoteOne {
    {"id":1,"title":"ship canon v1"} -> Body
}

Unit => NoteTwo {
    {"id":2,"title":"write the docs"} -> Body
}

Request => Response {
    Request.path() -> (
        * None { Status(400) -> Response(Headers() * NotFound()) }
        * Some<String> {
            String -> (
                * "/notes" { Status(200) -> Response(Headers() * IndexBody()) }
                * "/notes/1" { Status(200) -> Response(Headers() * NoteOne()) }
                * "/notes/2" { Status(200) -> Response(Headers() * NoteTwo()) }
                * String { Status(404) -> Response(Headers() * NotFound()) }
            )
        }
    )
}
