Flipped = Line

Line = String

RenderedItem = Html

Line => Flipped {
    Line -> ByteAt(1) -> Eq(48) -> (
        * False { Line(`0{Line -> Substring(From(2) * Line -> Length -> To)}`) }
        * True { Line(`1{Line -> Substring(From(2) * Line -> Length -> To)}`) }
    )
}

Int * Line => RenderedItem {
    Line -> ByteAt(1) -> Eq(49) -> (
        * False {
            Li(`{Line -> Substring(From(3) * Line -> Length -> To) -> Escaped} {
                Msg(`Toggle:{Int -> String}`) -> Button("done")
            } {Msg(`Delete:{Int -> String}`) -> Button("remove")}`)
        }
        * True {
            Li(`<s>{Line -> Substring(From(3) * Line -> Length -> To) -> Escaped}</s> {
                Msg(`Toggle:{Int -> String}`) -> Button("undo")
            } {Msg(`Delete:{Int -> String}`) -> Button("remove")}`)
        }
    )
}
