PlainText = Headers

Unit => PlainText {
    Headers().set("content-type" * "text/plain")
}

Request => Response {
    Request.method() -> (
        * "GET" {
            Request.path() -> (
                * None { Body("bad request") -> Response(Status(400) * PlainText()) }
                * Some<String> {
                    String -> (
                        * "/todos" {
                            Status(200) -> Response(PlainText() * Seeded() -> String -> Body)
                        }
                        * String { Body("not found") -> Response(Status(404) * PlainText()) }
                    )
                }
            )
        }
        * String { Body("method not allowed") -> Response(Status(405) * PlainText()) }
    )
}
