AddedTodo = Todos

Cleared = Todos

Done = Bool

RemovedAt = Todos

RenderedItems = Html

Todo = Done * Title

Todos = List<Todo>

ToggledAt = Todos

Title * Todos => AddedTodo {
    Todos
        -> Appended(False() -> Todo(Title))
        -> Todos
}

Todos => Cleared {
    Todos
        -> Filtered((Todo) => Bool { Todo.Done -> Not })
        -> Todos
}

Int * Todos => RemovedAt {
    Todos -> First -> (
        * None { Todos }
        * Some<Todo> {
            Int -> Eq(1) -> (
                * False {
                    List(Todo)
                        -> Joined(Int -> Difference(1) -> RemovedAt(Todos -> Skipped(1) -> Todos))
                        -> Todos
                }
                * True { Todos -> Skipped(1) -> Todos }
            )
        }
    )
}

Int * Todos => RenderedItems {
    Todos -> First -> (
        * None { Html("") }
        * Some<Todo> {
            Int
                -> RenderedItem(Todo)
                -> String
                -> Joined(Int -> Sum(1) -> RenderedItems(Todos -> Skipped(1) -> Todos) -> String)
                -> Html
        }
    )
}

Int * Todos => ToggledAt {
    Todos -> First -> (
        * None { Todos }
        * Some<Todo> {
            Int -> Eq(1) -> (
                * False {
                    List(Todo)
                        -> Joined(Int -> Difference(1) -> ToggledAt(Todos -> Skipped(1) -> Todos))
                        -> Todos
                }
                * True {
                    List(Todo.Done -> Not -> Done -> Todo(Todo.Title))
                        -> Joined(Todos -> Skipped(1))
                        -> Todos
                }
            )
        }
    )
}
