Add = String

Clear = Unit

Delete = Int

Done = Bool

RenderedItems = Html

Todo = Done * Title

Todos = List<Todo>

Toggle = Int

Int * Todos => RenderedItems {
    Todos -> First -> (
        * None { Html("") }
        * Some<Todo> {
            Int
                -> RenderedItem(Todo)
                -> String
                -> Joined(Int -> Sum(1) -> RenderedItems(Todos -> Skipped(1) -> Todos) -> String)
                -> Html
        }
    )
}

Todos * Add => Todos {
    Todos
        -> Appended(False() -> Todo(Add -> Title))
        -> Todos
}

Todos * Clear => Todos {
    Todos
        -> Filtered((Todo) => Bool { Todo.Done -> Not })
        -> Todos
}

Todos * Delete => Todos {
    Todos -> First -> (
        * None { Todos }
        * Some<Todo> {
            Delete -> Eq(1) -> (
                * False {
                    List(Todo)
                        -> Joined(Todos -> Skipped(1) -> Todos -> Delete(Delete -> Difference(1)))
                        -> Todos
                }
                * True { Todos -> Skipped(1) -> Todos }
            )
        }
    )
}

Todos * Toggle => Todos {
    Todos -> First -> (
        * None { Todos }
        * Some<Todo> {
            Toggle -> Eq(1) -> (
                * False {
                    List(Todo)
                        -> Joined(Todos -> Skipped(1) -> Todos -> Toggle(Toggle -> Difference(1)))
                        -> Todos
                }
                * True {
                    List(Todo.Done -> Not -> Done -> Todo(Todo.Title))
                        -> Joined(Todos -> Skipped(1))
                        -> Todos
                }
            )
        }
    )
}
