AddForm = ElAttr

ClearButton = Button

Init = Todos

LoadButton = ElAttr

Prefix = String

Unit => AddForm {
    Attr("data-msg-form=\"Add:\"")
        -> ElAttr(
            Attr("placeholder=\"What needs doing?\"") -> ElAttr("" * Tag("input"))
            * Tag("form")
        )
}

Unit => ClearButton {
    Msg("Clear") -> Button("Clear completed")
}

Todos => Html {
    Div(`<h1>Canon Todos</h1>{AddForm() -> String}{1 -> RenderedItems(Todos) -> Ul}{
        ClearButton() -> String
    }{LoadButton() -> String}`)
}

Unit => Init {
    List(False() -> Todo(Title("build the canon frontend")) * False() -> Todo(Title("check the canon backend")))
        -> Todos
}

Unit => LoadButton {
    Attr("data-fetch=\"/todos\" data-fetch-msg=\"Load:\"")
        -> ElAttr("Load todos from the server" * Tag("button"))
}

Todos * Msg => Todos {
    Msg -> Substring(From(1) * To(4)) -> Prefix -> (
        * "Add:" { Todos -> Add(Msg -> Substring(From(5) * Msg -> Length -> To)) }
        * "Clea" { Todos -> Clear }
        * "Dele" {
            Msg -> Substring(From(8) * Msg -> Length -> To) -> Int -> (
                * Err<MalformedInt> { Todos }
                * Ok<Int> { Todos -> Delete(Int) }
            )
        }
        * "Load" { Msg -> Substring(From(6) * Msg -> Length -> To) -> Wire -> Todos }
        * "Togg" {
            Msg -> Substring(From(8) * Msg -> Length -> To) -> Int -> (
                * Err<MalformedInt> { Todos }
                * Ok<Int> { Todos -> Toggle(Int) }
            )
        }
        * Prefix { Todos }
    )
}
