Line = String

Parsed = Todo

RenderedItem = Html

Wire = String

Todo => Line {
    Todo.Done -> (
        * False { `0|{Todo.Title}` }
        * True { `1|{Todo.Title}` }
    )
}

Line => Parsed {
    Line
        -> ByteAt(1)
        -> Eq(49)
        -> Done
        -> Todo(Line -> Substring(From(3) * Line -> Length -> To) -> Title)
}

Int * Todo => RenderedItem {
    Todo.Done -> (
        * False {
            Li(`{Todo.Title -> Escaped} {Msg(`Toggle:{Int -> String}`) -> Button("done")} {
                Msg(`Delete:{Int -> String}`) -> Button("remove")
            }`)
        }
        * True {
            Li(`<s>{Todo.Title -> Escaped}</s> {Msg(`Toggle:{Int -> String}`) -> Button("undo")} {
                Msg(`Delete:{Int -> String}`) -> Button("remove")
            }`)
        }
    )
}

Wire => Todos {
    Wire.String
        -> Lines
        -> Filtered((String) => Bool { String -> Length -> Gt(0) })
        -> Mapped((String) => Parsed { String -> Line -> Parsed })
        -> Todos
}

Todos => Wire {
    Todos -> Folded(Wire("") * (Todo * Wire) => Wire { Wire(`{Wire}{Todo -> Line}\n`) })
}
