JsonEntry = String

JsonMissing = String

JsonObject = JsonEntry

JsonValue = JsonMissing + JsonObject

Described = (JsonValue) => Unit {
    JsonValue -> (
        * JsonMissing => Unit { "missing" -> Print }
        * JsonObject => Unit { JsonObject -> Extracted -> Print }
    )
}

Extracted = (JsonObject) => String {
    "extracted"
}

Unit => Program {
    "payload"
        -> JsonEntry
        -> JsonObject
        -> Described
    "ok" -> Print
}
