Path = String

classify = (Int) => String {
    Int -> (
        * 0 => String { "zero" }
        * 1 => String { "one" }
        * Int => String { "many" }
    )
}

route = (Path) => String {
    Path -> (
        * "/" => String { "home" }
        * "/notes" => String { "index" }
        * Path => String { "not found" }
    )
}

Unit => Program {
    "/notes"
        -> Path
        .route()
        -> Print
    2
        .classify()
        -> Print
}
