Classified = String

Path = String

Routed = String

Int => Classified {
    Int -> (
        * 0 => Classified { "zero" }
        * 1 => Classified { "one" }
        * Int => Classified { "many" }
    )
}

Path => Routed {
    Path -> (
        * "/" => Routed { "home" }
        * "/notes" => Routed { "index" }
        * Path => Routed { "not found" }
    )
}

Unit => Program {
    Path("/notes")
        -> Routed
        -> Print
    Classified(2) -> Print
}
