Model = Int

init = () -> Model {
    Model(0)
}

update = (Model * String) -> Model {
    String.(
        * ("Decrement") -> Model { Model(Model.sub(1)) }
        * ("Increment") -> Model { Model(Model.add(1)) }
        * (String) -> Model { Model }
    )
}

view = (Model) -> Html {
    "Canon Counter"
        .H1()
        .concat(Msg("Decrement").Button("-"))
        .concat(Model.String().Span())
        .concat(Msg("Increment").Button("+"))
        .Div()
}
