Unit => Result<Program, Unit> {
    "model" -> Ok -> (
        * Err<Unit> => Unit { "err" -> Print }
        * Ok<String> => Unit {
            "first: "
                -> Joined("literal")
                -> Print
            String -> Print
            "echo: "
                -> Joined(String)
                -> Joined(":")
                -> Joined(String)
                -> Print
        }
    )
    Unit() -> Ok
}
