Unit => Program {
    True() -> Print
    False() -> Print
    True()
        -> And(False())
        -> Print
    True()
        -> And(True())
        -> Print
    False()
        -> Or(True())
        -> Print
    True()
        -> Not
        -> Print
    1
        -> Eq(1)
        -> And(2 -> Eq(2))
        -> Print
    1
        -> Eq(2)
        -> Or(1 -> Eq(1))
        -> Not
        -> Print
}
