Greeting = String

Loud = String

Int => Greeting {
    Greeting("int:" -> Joined(Int -> String))
}

Greeting => Loud {
    Loud(Greeting.String -> Joined("!"))
}

main = () => Unit {
    7
        -> Greeting
        -> Loud
        -> Print
    "41"
        -> Int?
        -> Sum(1)
        -> Print
    Map()
        -> Inserted("a" * "1")
        -> Keys
        -> Json
        -> Print
    Map() -> Inserted("k" * "v") -> Value("k").(
        * None => Unit { "none" -> Print }
        * Some<String> => Unit { String -> Print }
    )
}
