Greeting = String

Greeting = () => Greeting {
    "hello" -> Greeting
}

Greeting = (Bool) => Greeting {
    Bool -> (
        * False => Greeting { "bool:no" -> Greeting }
        * True => Greeting { "bool:yes" -> Greeting }
    )
}

Greeting = (Int) => Greeting {
    "int:"
        -> Joined(Int -> String)
        -> Greeting
}

main = () => Unit {
    Greeting() -> Print
    7
        -> Greeting
        -> Print
    True()
        -> Greeting
        -> Print
    7
        -> Greeting
        -> Print
}
