Greeting = String

Unit => Greeting {
    "hello" -> Greeting
}

Bool => Greeting {
    Bool -> (
        * False => Greeting { "bool:no" -> Greeting }
        * True => Greeting { "bool:yes" -> Greeting }
    )
}

Int => Greeting {
    "int:"
        -> Joined(Int -> String)
        -> Greeting
}

Unit => Program {
    Greeting() -> Print
    7
        -> Greeting
        -> Print
    True()
        -> Greeting
        -> Print
    7
        -> Greeting
        -> Print
}
