Greeting = String

Unit => Greeting {
    Greeting("hello")
}

Bool => Greeting {
    Bool -> (
        * False => Greeting { Greeting("bool:no") }
        * True => Greeting { Greeting("bool:yes") }
    )
}

Int => Greeting {
    "int:"
        -> Joined(Int -> String)
        -> Greeting
}

Unit => Program {
    Greeting() -> Print
    Greeting(7) -> Print
    True()
        -> Greeting
        -> Print
    Greeting(7) -> Print
}
