Greeting = String

() => Greeting {
    Greeting("hello")
}

(Bool) => Greeting {
    Bool.(
        * (False) => Greeting { Greeting("bool:no") }
        * (True) => Greeting { Greeting("bool:yes") }
    )
}

(Int) => Greeting {
    Greeting("int:" -> Joined(Int -> String))
}

main = () => Unit {
    Greeting() -> Print
    Greeting(7) -> Print
    Greeting(True()) -> Print
    7
        -> Greeting
        -> Print
}
