Greeting = String

Loud = String

(Int) -> Greeting {
    Greeting("int:".concat(Int.String()))
}

(Greeting) -> Loud {
    Loud(Greeting.String.concat("!"))
}

main = () -> Unit {
    7
        -> Greeting
        -> Loud
        .print()
    "41"
        -> Int?
        .add(1)
        .print()
    Map()
        .Inserted("a", "1")
        -> Keys
        -> Json
        .print()
    Map().Inserted("k", "v") -> Value("k").(
        * (None) -> Unit { "none".print() }
        * (Some<String>) -> Unit { String.print() }
    )
}
