Greeting = String

Loud = String

Int => Greeting {
    Greeting(`int:{Int -> String}`)
}

Greeting => Loud {
    Loud(`{Greeting.String}!`)
}

Unit => Program {
    Greeting(7)
        -> Loud
        -> Print
    Int("41")?
        -> Sum(1)
        -> Print
    Map()
        -> Inserted("a" * "1")
        -> Keys
        -> Json
        -> Print
    Map() -> Inserted("k" * "v") -> Value("k") -> (
        * None => Unit { "none" -> Print }
        * Some<String> => Unit { String -> Print }
    )
}
