Unit => Program {
    2.5
        -> Lt(3.5)
        -> Print
    3.5
        -> Le(3.5)
        -> Print
    4.5
        -> Gt(3.5)
        -> Print
    3.5
        -> Ge(4.5)
        -> Print
    2.5
        -> Eq(2.5)
        -> Print
    2.5
        -> Ne(2.5)
        -> Print
    7.5
        -> Remainder(2.0)
        -> Print
    0.0
        -> Difference(7.5)
        -> Remainder(2.0)
        -> Print
}
