Entry<K, V> = Key<K> * Rest<K, V> * Value<V>

Inserted<K, V> = Store<K, V>

Key<K> = K

Rest<K, V> = Store<K, V>

Size<K, V> = Int

Store<K, V> = Absent + Entry<K, V>

Value<V> = V

<K, V>(Store<K, V> * K * V) => Inserted<K, V> {
    K
        -> Key
        -> Entry(Store -> Rest * V -> Value)
}

<K, V>(Store<K, V>) => Size<K, V> {
    Store -> (
        * Absent { 0 }
        * Entry { Entry.Rest -> Size -> Sum(1) }
    )
}

<K, V>(Unit) => Store<K, V> {
    Absent()
}

Unit => Program {
    Store<String, Int>()
        -> Inserted("a" * 1)
        -> Inserted("b" * 2)
        -> Size
        -> String
        -> Print
    Store<Int, String>()
        -> Inserted(1 * "one")
        -> Size
        -> String
        -> Print
}
