main = () => Unit {
    "42" -> Int -> (
        * Err<MalformedInt> => Unit { "err" -> Print }
        * Ok<Int> => Unit { Int -> Print }
    )
    "-7" -> Int -> (
        * Err<MalformedInt> => Unit { "err" -> Print }
        * Ok<Int> => Unit { Int -> Print }
    )
    "123" -> Int -> (
        * Err<MalformedInt> => Unit { "err" -> Print }
        * Ok<Int> => Unit { Int -> Print }
    )
    "abc" -> Int -> (
        * Err<MalformedInt> => Unit { MalformedInt -> Print }
        * Ok<Int> => Unit { Int -> Print }
    )
    "" -> Int -> (
        * Err<MalformedInt> => Unit { MalformedInt -> Print }
        * Ok<Int> => Unit { Int -> Print }
    )
}
