Doubled = Int

String => Result<Doubled, MalformedInt> {
    String
        -> Int?
        -> Product(2)
        -> Ok
}

Unit => Program {
    Doubled("21") -> (
        * Err<MalformedInt> => Unit { "err" -> Print }
        * Ok<Int> => Unit { Int -> Print }
    )
    Doubled("x") -> (
        * Err<MalformedInt> => Unit { MalformedInt -> Print }
        * Ok<Int> => Unit { Int -> Print }
    )
}
