Doubled = (String) => Result<Int, MalformedInt> {
    String
        -> Int?
        -> Product(2)
        -> Ok
}

Unit => Program {
    "21" -> Doubled -> (
        * Err<MalformedInt> => Unit { "err" -> Print }
        * Ok<Int> => Unit { Int -> Print }
    )
    "x" -> Doubled -> (
        * Err<MalformedInt> => Unit { MalformedInt -> Print }
        * Ok<Int> => Unit { Int -> Print }
    )
}
