Unit => Program {
    Map<String, String>()
        -> Insert(Key("b") * Value("banana"))
        -> Insert(Key("a") * Value("apple"))
        -> Value("a") -> (
        * None => Unit { "none" -> Print }
        * Some<String> => Unit { String -> Print }
    )
    Map<String, String>()
        -> Insert(Key("k") * Value("v1"))
        -> Insert(Key("k") * Value("v2"))
        -> Value("k") -> (
        * None => Unit { "none" -> Print }
        * Some<String> => Unit { String -> Print }
    )
    Map<String, String>() -> Insert(Key("a") * Value("1")) -> Value("missing") -> (
        * None => Unit { "none" -> Print }
        * Some<String> => Unit { String -> Print }
    )
    Map<String, String>()
        -> Insert(Key("a") * Value("1"))
        -> Insert(Key("b") * Value("2"))
        -> Length
        -> Print
    Map<String, String>()
        -> Insert(Key("a") * Value("1"))
        -> Insert(Key("b") * Value("2"))
        -> Remove("a")
        -> Length
        -> Print
    Map<String, String>()
        -> Insert(Key("a") * Value("1"))
        -> Insert(Key("b") * Value("2"))
        -> Keys
        -> Json
        -> Print
    Map<String, String>()
        -> Insert(Key("a") * Value("1"))
        -> Insert(Key("b") * Value("2"))
        -> Values
        -> Json
        -> Print
    Map<String, String>()
        -> Insert(Key("a") * Value("1"))
        -> Remove("missing")
        -> Length
        -> Print
    Map<String, String>()
        -> Insert(Key("b") * Value("2"))
        -> Insert(Key("c") * Value("3"))
        -> Insert(Key("a") * Value("1"))
        -> Keys
        -> Json
        -> Print
    Map<String, String>()
        -> Insert(Key("b") * Value("2"))
        -> Insert(Key("c") * Value("3"))
        -> Insert(Key("a") * Value("1"))
        -> Values
        -> Json
        -> Print
}
