Unit => Program {
    Map()
        -> Inserted(Key("b") * Value("banana"))
        -> Inserted(Key("a") * Value("apple"))
        -> Value("a") -> (
        * None => Unit { "none" -> Print }
        * Some<String> => Unit { String -> Print }
    )
    Map() -> Inserted(Key("k") * Value("v1")) -> Inserted(Key("k") * Value("v2")) -> Value("k") -> (
        * None => Unit { "none" -> Print }
        * Some<String> => Unit { String -> Print }
    )
    Map() -> Inserted(Key("a") * Value("1")) -> Value("missing") -> (
        * None => Unit { "none" -> Print }
        * Some<String> => Unit { String -> Print }
    )
    Map()
        -> Inserted(Key("a") * Value("1"))
        -> Inserted(Key("b") * Value("2"))
        -> Length
        -> Print
    Map()
        -> Inserted(Key("a") * Value("1"))
        -> Inserted(Key("b") * Value("2"))
        -> Removed("a")
        -> Length
        -> Print
    Map()
        -> Inserted(Key("a") * Value("1"))
        -> Inserted(Key("b") * Value("2"))
        -> Keys
        -> Json
        -> Print
    Map()
        -> Inserted(Key("a") * Value("1"))
        -> Inserted(Key("b") * Value("2"))
        -> Values
        -> Json
        -> Print
    Map()
        -> Inserted(Key("a") * Value("1"))
        -> Removed("missing")
        -> Length
        -> Print
    Map()
        -> Inserted(Key("b") * Value("2"))
        -> Inserted(Key("c") * Value("3"))
        -> Inserted(Key("a") * Value("1"))
        -> Keys
        -> Json
        -> Print
    Map()
        -> Inserted(Key("b") * Value("2"))
        -> Inserted(Key("c") * Value("3"))
        -> Inserted(Key("a") * Value("1"))
        -> Values
        -> Json
        -> Print
}
