First = String

Second = String

Int => Option<First> {
    Int -> Eq(0) -> (
        * False => Option<First> { Some("found") }
        * True => Option<First> { None() }
    )
}

Int => Option<Second> {
    Some(`{Int -> First?} and used`)
}

Unit => Program {
    Second(5) -> (
        * None => Unit { "none" -> Print }
        * Some<String> => Unit { String -> Print }
    )
    Second(0) -> (
        * None => Unit { "none" -> Print }
        * Some<String> => Unit { String -> Print }
    )
}
