Picked = (Int) => Option<String> {
    Int -> Eq(0) -> (
        * False => Option<String> { "payload" -> Some }
        * True => Option<String> { None() }
    )
}

Unit => Program {
    1 -> Picked -> (
        * None => Unit { "none" -> Print }
        * Some<String> => Unit { String -> Print }
    )
    0 -> Picked -> (
        * None => Unit { "none" -> Print }
        * Some<String> => Unit { String -> Print }
    )
}
