CompletionTokens = Int

PromptTokens = Int

TotalTokens = Int

Usage = CompletionTokens * PromptTokens * TotalTokens

Unit => Program {
    CompletionTokens(11) -> Usage(PromptTokens(22) * TotalTokens(33)).CompletionTokens -> Print
    CompletionTokens(11) -> Usage(PromptTokens(22) * TotalTokens(33)).PromptTokens -> Print
    CompletionTokens(11) -> Usage(PromptTokens(22) * TotalTokens(33)).TotalTokens -> Print
}
