CompletionTokens = Int

PromptTokens = Int

TotalTokens = Int

Usage = CompletionTokens * PromptTokens * TotalTokens

main = () => Unit {
    11 -> CompletionTokens -> Usage(22 -> PromptTokens * 33 -> TotalTokens).CompletionTokens
        -> Print
    11 -> CompletionTokens -> Usage(22 -> PromptTokens * 33 -> TotalTokens).PromptTokens -> Print
    11 -> CompletionTokens -> Usage(22 -> PromptTokens * 33 -> TotalTokens).TotalTokens -> Print
}
