Chain = Link + Stop

Label = String

Link = Label * Next

Next = Chain

lastLabel = (Chain) -> String {
    Chain.(
        * (Link) -> String {
            Link.Next.len().eq(0).(
                * (False) -> String { Link.Next.lastLabel() }
                * (True) -> String { Link.Label }
            )
        }
        * (Stop) -> String { "" }
    )
}

len = (Chain) -> Int {
    Chain.(
        * (Link) -> Int { Link.Next.len().add(1) }
        * (Stop) -> Int { 0 }
    )
}

main = () -> Unit {
    Link("a", Link("b", Link("c", Stop())))
        .len()
        .print()
    Link("a", Link("b", Stop()))
        .lastLabel()
        .print()
}
