Chain = Link + Stop

Label = String

Link = Label * Next

Next = Chain

lastLabel = (Chain) => String {
    Chain.(
        * Link => String {
            Link.Next.len() -> Eq(0).(
                * False => String { Link.Next.lastLabel() }
                * True => String { Link.Label }
            )
        }
        * Stop => String { "" }
    )
}

len = (Chain) => Int {
    Chain.(
        * Link => Int { Link.Next.len() -> Sum(1) }
        * Stop => Int { 0 }
    )
}

main = () => Unit {
    Link("a", Link("b", Link("c", Stop())))
        .len()
        -> Print
    Link("a", Link("b", Stop()))
        .lastLabel()
        -> Print
}
