Code = Int

HttpError = Code * Reason

Lookup = Reason

Missing = String

Printed = Unit

Reason = String

Bool => Result<Lookup, Missing> {
    Bool -> (
        * False => Result<Lookup, Missing> { "user.name" -> Missing -> Err }
        * True => Result<Lookup, Missing> { "ada" -> Reason -> Ok }
    )
}

HttpError => Printed {
    "http "
        -> Joined(HttpError.Code -> String)
        -> Joined(": ")
        -> Joined(HttpError.Reason)
        -> Printed
}

Missing => Printed {
    "missing key: "
        -> Joined(Missing)
        -> Printed
}

Unit => Program {
    500
        -> Code
        -> HttpError("boom" -> Reason)
        -> Printed
    True() -> Lookup -> (
        * Err<Missing> => Unit { Missing -> Printed }
        * Ok<Reason> => Unit { Reason -> Printed }
    )
    False() -> Lookup -> (
        * Err<Missing> => Unit { Missing -> Printed }
        * Ok<Reason> => Unit { Reason -> Printed }
    )
}
