Unit => Program {
    Set()
        -> Added("b")
        -> Added("a")
        -> Added("b")
        -> Length
        -> Print
    Set()
        -> Added("x")
        -> Contains("x")
        -> Print
    Set()
        -> Added("x")
        -> Contains("y")
        -> Print
    Set()
        -> Added("b")
        -> Added("c")
        -> Added("a")
        -> List
        -> Json
        -> Print
    Set()
        -> Added("a")
        -> Added("b")
        -> Dropped("a")
        -> List
        -> Json
        -> Print
    Set()
        -> Added("a")
        -> Dropped("missing")
        -> Length
        -> Print
}
