Unit => Program {
    "apple"
        -> Lt("banana")
        -> Print
    "banana"
        -> Lt("apple")
        -> Print
    "app"
        -> Lt("apple")
        -> Print
    "apple"
        -> Le("apple")
        -> Print
    "apple"
        -> Ge("banana")
        -> Print
    "banana"
        -> Gt("apple")
        -> Print
    "apple"
        -> Ne("banana")
        -> Print
    "apple"
        -> Ne("apple")
        -> Print
}
