main = () => Unit {
    "hello"
        -> Length
        -> Print
    "hello"
        -> ByteAt(1)
        -> Print
    "hello"
        -> ByteAt(5)
        -> Print
    "hello"
        -> Substring(From(2) * To(4))
        -> Print
    "hello" -> Eq("hello") -> (
        * False => Unit { "ne" -> Print }
        * True => Unit { "eq" -> Print }
    )
    "hello" -> Eq("world") -> (
        * False => Unit { "ne" -> Print }
        * True => Unit { "eq" -> Print }
    )
    "hello" -> Eq("hell") -> (
        * False => Unit { "ne" -> Print }
        * True => Unit { "eq" -> Print }
    )
}
