Equal = Unit

Greater = Unit

Less = Unit

Ord = Equal
  + Greater
  + Less

Unit => Program {
    Equal() -> (
        * Equal => Unit { "equal" -> Print }
        * Greater => Unit { "greater" -> Print }
        * Less => Unit { "less" -> Print }
    )
    Greater() -> (
        * Equal => Unit { "equal" -> Print }
        * Greater => Unit { "greater" -> Print }
        * Less => Unit { "less" -> Print }
    )
    Less() -> (
        * Equal => Unit { "equal" -> Print }
        * Greater => Unit { "greater" -> Print }
        * Less => Unit { "less" -> Print }
    )
}
