Equal = Unit

Greater = Unit

Less = Unit

Ord = Equal
  + Greater
  + Less

main = () => Unit {
    Equal().(
        * (Equal) => Unit { "equal".print() }
        * (Greater) => Unit { "greater".print() }
        * (Less) => Unit { "less".print() }
    )
    Greater().(
        * (Equal) => Unit { "equal".print() }
        * (Greater) => Unit { "greater".print() }
        * (Less) => Unit { "less".print() }
    )
    Less().(
        * (Equal) => Unit { "equal".print() }
        * (Greater) => Unit { "greater".print() }
        * (Less) => Unit { "less".print() }
    )
}
