Branch = Left * Right * Value

Left = Tree

Right = Tree

Tree = Branch + Leaf

Value = Int

describe = (Tree) => String {
    Tree -> (
        * Branch => String { "branch" }
        * Leaf => String { "leaf" }
    )
}

Unit => Program {
    Leaf()
        .describe()
        -> Print
    7
        -> Value
        -> Branch(Leaf() -> Left * Leaf() -> Right)
        .describe()
        -> Print
}
