classify = (Int) => Result<String, String> {
    Int -> Eq(0) -> (
        * False => Result<String, String> { Ok("nonzero") }
        * True => Result<String, String> { Err("was zero") }
    )
}

describe = (Int) => Result<String, String> {
    Ok(Int.classify()? -> Joined(" indeed"))
}

main = () => Unit {
    3.describe() -> (
        * Err<String> => Unit { String -> Print }
        * Ok<String> => Unit { String -> Print }
    )
    0.describe() -> (
        * Err<String> => Unit { String -> Print }
        * Ok<String> => Unit { String -> Print }
    )
}
