classify = (Int) => Result<String, String> {
    Int -> Eq(0) -> (
        * False => Result<String, String> { "nonzero" -> Ok }
        * True => Result<String, String> { "was zero" -> Err }
    )
}

describe = (Int) => Result<String, String> {
    Int
        .classify()?
        -> Joined(" indeed")
        -> Ok
}

Unit => Program {
    3.describe() -> (
        * Err<String> => Unit { String -> Print }
        * Ok<String> => Unit { String -> Print }
    )
    0.describe() -> (
        * Err<String> => Unit { String -> Print }
        * Ok<String> => Unit { String -> Print }
    )
}
