Classified = (Int) => Result<String, String> {
    Int -> Eq(0) -> (
        * False => Result<String, String> { "nonzero" -> Ok }
        * True => Result<String, String> { "was zero" -> Err }
    )
}

Described = (Int) => Result<String, String> {
    Int
        -> Classified?
        -> Joined(" indeed")
        -> Ok
}

Unit => Program {
    3 -> Described -> (
        * Err<String> => Unit { String -> Print }
        * Ok<String> => Unit { String -> Print }
    )
    0 -> Described -> (
        * Err<String> => Unit { String -> Print }
        * Ok<String> => Unit { String -> Print }
    )
}
