Count = Int

Empty = Unit

MadeCount = Shape

MadeEmpty = Shape

MadeName = Shape

MadeRatio = Shape

Name = String

Ratio = Float

Shape = Count
  + Empty
  + Name
  + Ratio

Shown = Unit

Unit => MadeCount {
    42 -> Count
}

Unit => MadeEmpty {
    Empty()
}

Unit => MadeName {
    "alex" -> Name
}

Unit => MadeRatio {
    2.5 -> Ratio
}

Shape => Shown {
    Shape -> (
        * Count => Unit { Count -> Print }
        * Empty => Unit { "empty" -> Print }
        * Name => Unit { Name -> Print }
        * Ratio => Unit { Ratio -> Print }
    )
}

Unit => Program {
    MadeCount() -> Shown
    MadeEmpty() -> Shown
    MadeName() -> Shown
    MadeRatio() -> Shown
}
