Count = Int

Empty = Unit

Name = String

Ratio = Float

Shape = Count
  + Empty
  + Name
  + Ratio

makeCount = () => Shape {
    42 -> Count
}

makeEmpty = () => Shape {
    Empty()
}

makeName = () => Shape {
    "alex" -> Name
}

makeRatio = () => Shape {
    2.5 -> Ratio
}

show = (Shape) => Unit {
    Shape -> (
        * Count => Unit { Count -> Print }
        * Empty => Unit { "empty" -> Print }
        * Name => Unit { Name -> Print }
        * Ratio => Unit { Ratio -> Print }
    )
}

Unit => Program {
    makeCount().show()
    makeEmpty().show()
    makeName().show()
    makeRatio().show()
}
