Reported = Unit

String => Reported {
    String -> Url -> (
        * Err<InvalidUrl> => Reported { InvalidUrl -> Print }
        * Ok<Url> => Reported { Url -> Print }
    )
}

Unit => Program {
    "http://example.com/path" -> Reported
    "https://example.com" -> Reported
    "ftp://example.com" -> Reported
    "http://" -> Reported
    "http:///path" -> Reported
    "https://x" -> Reported
}
