Fail = String

Pass = Unit

TestResult = Fail + Pass

makeFail = () => TestResult {
    "the message" -> Fail
}

makePass = () => TestResult {
    Pass()
}

Unit => Program {
    makeFail() -> (
        * Fail => Unit { Fail -> Print }
        * Pass => Unit { "got pass" -> Print }
    )
    makePass() -> (
        * Fail => Unit { Fail -> Print }
        * Pass => Unit { "got pass" -> Print }
    )
}
