Fail = String

MakeFail = TestResult

MakePass = TestResult

Pass = Unit

TestResult = Fail + Pass

Unit => MakeFail {
    Fail("the message")
}

Unit => MakePass {
    Pass()
}

Unit => Program {
    MakeFail() -> (
        * Fail => Unit { Fail -> Print }
        * Pass => Unit { "got pass" -> Print }
    )
    MakePass() -> (
        * Fail => Unit { Fail -> Print }
        * Pass => Unit { "got pass" -> Print }
    )
}
