id = "oneway"
name = "Oneway"
version = "0.3.0"
schema_version = 1
authors = ["Oneway Contributors"]
description = "Oneway language support for Zed"

[grammars.oneway]
repository = "https://github.com/Almaju/oneway"
path = "editors/tree-sitter-oneway"
commit = "e2c1cd3bcd43f9dc9359d65d26ea605805340566"
