AndOfFalseIsFalse = () => TestResult {
    True()
        -> And(False())
        -> Not
        -> TestResult
}

AndOfTruesIsTrue = () => TestResult {
    True()
        -> And(True())
        -> TestResult
}

AndShortCircuitsOnFalse = () => TestResult {
    False()
        -> And(True())
        -> Not
        -> TestResult
}

NotOfFalseIsTrue = () => TestResult {
    False()
        -> Not
        -> TestResult
}

NotOfTrueIsFalse = () => TestResult {
    True()
        -> Not
        -> Not
        -> TestResult
}

OrOfFalsesIsFalse = () => TestResult {
    False()
        -> Or(False())
        -> Not
        -> TestResult
}

OrShortCircuitsOnTrue = () => TestResult {
    True()
        -> Or(False())
        -> TestResult
}

OrWithTrueIsTrue = () => TestResult {
    False()
        -> Or(True())
        -> TestResult
}
