Greeted = Greeting

Greeting = String

Name = String

Greeted = (Greeting * Name) => Greeted {
    Greeting
}

testCallableBothWays = () => TestResult {
    "hello"
        -> Greeting
        -> Greeted("world" -> Name)
    "world"
        -> Name
        -> Greeted("hello" -> Greeting)
    Pass()
}

testCanonicalDirection = () => TestResult {
    "hello"
        -> Greeting
        -> Greeted("world" -> Name)
    Pass()
}

testNonCanonicalDirection = () => TestResult {
    "world"
        -> Name
        -> Greeted("hello" -> Greeting)
    Pass()
}
