Greeted = Greeting

Greeting = String

Name = String

Greeted = (Greeting * Name) => Greeted {
    Greeting
}

testCallableBothWays = () => TestResult {
    Greeting("hello") -> Greeted(Name("world"))
    Name("world") -> Greeted(Greeting("hello"))
    Pass()
}

testCanonicalDirection = () => TestResult {
    Greeting("hello") -> Greeted(Name("world"))
    Pass()
}

testNonCanonicalDirection = () => TestResult {
    Name("world") -> Greeted(Greeting("hello"))
    Pass()
}
