Greeted = Greeting

Greeting = String

Name = String

Greeted = (Greeting * Name) => Greeted {
    Greeting
}

ProductCallableBothWays = () => TestResult {
    "hello"
        -> Greeting
        -> Greeted("world" -> Name)
    "world"
        -> Name
        -> Greeted("hello" -> Greeting)
    Pass()
}

ProductCanonicalDirection = () => TestResult {
    "hello"
        -> Greeting
        -> Greeted("world" -> Name)
    Pass()
}

ProductNonCanonicalDirection = () => TestResult {
    "world"
        -> Name
        -> Greeted("hello" -> Greeting)
    Pass()
}
