Dark = Unit

DispatchSelectsDarkArm = TestResult

DispatchSelectsLightArm = TestResult

Light = Unit

Unit => DispatchSelectsDarkArm {
    Dark() -> (
        * Dark => TestResult { Pass() }
        * Light => TestResult { Fail() }
    )
}

Mode = Dark + Light

Unit => DispatchSelectsLightArm {
    Light() -> (
        * Dark => TestResult { Fail() }
        * Light => TestResult { Pass() }
    )
}
