use std::convert::Infallible;
use std::sync::Arc;

// ── Request type ─────────────────────────────────────────────────────────────
// `OnewayHttpRequest` is the concrete Rust struct. The codegen emits
//   `pub type HttpRequest = oneway_http_request;`
// from `extern Rust("oneway_http_request") HttpRequest`, so we expose a
// lowercase type alias so the alias resolves correctly.

#[derive(Clone)]
pub struct OnewayHttpRequest {
    pub body: String,
    pub path: String,
}

#[allow(non_camel_case_types)]
pub type oneway_http_request = OnewayHttpRequest;

// `oneway_http_request_body` and `oneway_http_request_path` use `Body` and
// `String`. `Body` is generated by the codegen from `Body = String` in the
// .ow file (as `pub struct Body(pub String);`), so it is available later in
// the combined Rust source — Rust doesn't require forward declarations.

#[allow(dead_code)]
fn oneway_http_request_body(req: OnewayHttpRequest) -> Body {
    Body(req.body)
}

#[allow(dead_code)]
fn oneway_http_request_path(req: OnewayHttpRequest) -> String {
    req.path
}

// ── SSE ───────────────────────────────────────────────────────────────────────

/// The send-half of an SSE channel. Passed to SSE route handlers.
#[derive(Clone)]
pub struct OnewaySSeSender(pub tokio::sync::mpsc::UnboundedSender<String>);

#[allow(non_camel_case_types)]
pub type oneway_sse_sender = OnewaySSeSender;

// `SseData` is generated by the codegen from `SseData = String`.
#[allow(dead_code)]
fn oneway_sse_send(data: SseData, sender: OnewaySSeSender) {
    let _ = sender.0.send(data.0);
}

// ── Router ────────────────────────────────────────────────────────────────────

// Internal route entry — not part of the public Oneway API.
enum Route<S> {
    Http {
        path: String,
        method: HttpMethod,
        handler: Arc<dyn Fn(OnewayHttpRequest, S) -> HttpResponseBody + Send + Sync>,
    },
    Sse {
        path: String,
        handler: Arc<dyn Fn(OnewayHttpRequest, S, OnewaySSeSender) + Send + Sync>,
    },
}

enum HttpMethod {
    Get,
    Post,
}

// The codegen emits `pub type HttpRouter<S> = OnewayHttpRouter<S>;`
// from `extern Rust("OnewayHttpRouter") HttpRouter<S>` in the .ow file.
pub struct OnewayHttpRouter<S: Clone + Send + Sync + 'static> {
    routes: Vec<Route<S>>,
    state: Arc<S>,
}

impl<S: Clone + Send + Sync + 'static> Clone for OnewayHttpRouter<S> {
    fn clone(&self) -> Self {
        let routes = self
            .routes
            .iter()
            .map(|r| match r {
                Route::Http {
                    path,
                    method,
                    handler,
                } => Route::Http {
                    path: path.clone(),
                    method: match method {
                        HttpMethod::Get => HttpMethod::Get,
                        HttpMethod::Post => HttpMethod::Post,
                    },
                    handler: handler.clone(),
                },
                Route::Sse { path, handler } => Route::Sse {
                    path: path.clone(),
                    handler: handler.clone(),
                },
            })
            .collect();
        OnewayHttpRouter {
            routes,
            state: self.state.clone(),
        }
    }
}

// `Port` and `RoutePath` are generated by the codegen from `Port = Int` and
// `RoutePath = String`. `HttpServer` is a capability marker — not in
// http-server.ow as an Oneway type, so the codegen won't emit it; we define
// it here. The codegen does not emit anything for BUILTIN_TYPES.
pub struct HttpServer;

// `oneway_http_router_new` takes only the state (`S`). The `HttpServer`
// capability receiver is stripped by the codegen's extern-call emitter.
#[allow(dead_code)]
fn oneway_http_router_new<S: Clone + Send + Sync + 'static>(state: S) -> OnewayHttpRouter<S> {
    OnewayHttpRouter {
        routes: Vec::new(),
        state: Arc::new(state),
    }
}

// Note on handler parameter order: the codegen flattens product params left-to-right,
// so `(HttpRequest * S) -> HttpResponseBody` in the .ow file emits
// `|__a0: OnewayHttpRequest, __a1: S| -> HttpResponseBody { ... }`,
// matching the `fn(OnewayHttpRequest, S)` signature below.

#[allow(dead_code)]
fn oneway_http_get_route<S: Clone + Send + Sync + 'static>(
    mut router: OnewayHttpRouter<S>,
    path: RoutePath,
    handler: fn(OnewayHttpRequest, S) -> HttpResponseBody,
) -> OnewayHttpRouter<S> {
    router.routes.push(Route::Http {
        path: path.0,
        method: HttpMethod::Get,
        handler: Arc::new(move |req, state| handler(req, state)),
    });
    router
}

#[allow(dead_code)]
fn oneway_http_post_route<S: Clone + Send + Sync + 'static>(
    mut router: OnewayHttpRouter<S>,
    path: RoutePath,
    handler: fn(OnewayHttpRequest, S) -> HttpResponseBody,
) -> OnewayHttpRouter<S> {
    router.routes.push(Route::Http {
        path: path.0,
        method: HttpMethod::Post,
        handler: Arc::new(move |req, state| handler(req, state)),
    });
    router
}

#[allow(dead_code)]
fn oneway_http_sse_route<S: Clone + Send + Sync + 'static>(
    mut router: OnewayHttpRouter<S>,
    path: RoutePath,
    handler: fn(OnewayHttpRequest, S, OnewaySSeSender),
) -> OnewayHttpRouter<S> {
    router.routes.push(Route::Sse {
        path: path.0,
        handler: Arc::new(move |req, state, sender| handler(req, state, sender)),
    });
    router
}

// ── Serve ─────────────────────────────────────────────────────────────────────

#[allow(dead_code)]
async fn oneway_http_serve<S: Clone + Send + Sync + 'static>(
    router: OnewayHttpRouter<S>,
    port: Port,
) -> Result<(), std::io::Error> {
    use axum::body::Body as AxumBody;
    use axum::extract::Request;
    use axum::http::{Response, StatusCode};
    use axum::routing::{get, post};
    use axum::Router;

    let mut app: Router = Router::new();
    let state = router.state.clone();

    for route in router.routes {
        match route {
            Route::Http {
                path,
                method,
                handler,
            } => {
                let state = state.clone();
                let handler = handler.clone();
                let axum_handler = move |req: Request| {
                    let state = state.clone();
                    let handler = handler.clone();
                    async move {
                        let (parts, body) = req.into_parts();
                        let path_str = parts.uri.path().to_string();
                        let body_bytes = axum::body::to_bytes(body, usize::MAX)
                            .await
                            .unwrap_or_default();
                        let body_str = String::from_utf8_lossy(&body_bytes).into_owned();
                        let ow_req = OnewayHttpRequest {
                            body: body_str,
                            path: path_str,
                        };
                        let resp = handler(ow_req, (*state).clone());
                        // Field is `httpStatus` (camelCase) because the codegen emits
                        // `lower_first("HttpStatus")` = "httpStatus" for product fields.
                        #[allow(non_snake_case)]
                        let status = StatusCode::from_u16(resp.httpStatus.0 as u16)
                            .unwrap_or(StatusCode::OK);
                        Response::builder()
                            .status(status)
                            .body(AxumBody::from(resp.body.0))
                            .unwrap()
                    }
                };
                app = match method {
                    HttpMethod::Get => app.route(&path, get(axum_handler)),
                    HttpMethod::Post => app.route(&path, post(axum_handler)),
                };
            }
            Route::Sse { path, handler } => {
                use axum::response::sse::{Event, KeepAlive, Sse};
                use futures_util::stream::StreamExt;
                use tokio_stream::wrappers::UnboundedReceiverStream;

                let state = state.clone();
                let handler = handler.clone();
                let sse_handler = move |req: Request| {
                    let state = state.clone();
                    let handler = handler.clone();
                    async move {
                        let (parts, body) = req.into_parts();
                        let path_str = parts.uri.path().to_string();
                        let body_bytes = axum::body::to_bytes(body, usize::MAX)
                            .await
                            .unwrap_or_default();
                        let body_str = String::from_utf8_lossy(&body_bytes).into_owned();
                        let ow_req = OnewayHttpRequest {
                            body: body_str,
                            path: path_str,
                        };
                        let (tx, rx) = tokio::sync::mpsc::unbounded_channel::<String>();
                        let sender = OnewaySSeSender(tx);
                        let handler2 = handler.clone();
                        let s2 = (*state).clone();
                        tokio::task::spawn_blocking(move || {
                            handler2(ow_req, s2, sender);
                        });
                        let stream = UnboundedReceiverStream::new(rx)
                            .map(|data| Ok::<Event, Infallible>(Event::default().data(data)));
                        Sse::new(stream).keep_alive(KeepAlive::default())
                    }
                };
                app = app.route(&path, get(sse_handler));
            }
        }
    }

    let addr = format!("0.0.0.0:{}", port.0);
    let listener = tokio::net::TcpListener::bind(&addr).await?;
    axum::serve(listener, app).await
}
