//! `canon install` — materialize external bindings from the project's
//! `wit/` directory.
//!
//! External imports are declared by file structure, not by a manifest:
//! every immediate entry of `<project>/wit/` is one import source —
//! a directory of cross-referencing `.wit` files (the shape the real
//! WASI vendor tree uses), a single `.wit` file, or a `.wasm` component
//! (deferred until the composition pipeline lands). Putting a WIT
//! source under `wit/` *is* the import declaration; there is nothing
//! else to write.
//!
//! For each WIT source this generates one Canon file per interface,
//! writing them under the project's `bindgen/` directory at
//! `<namespace>/<package>@<version>/<iface>.can`. The output is the
//! same Canon source `canon bindgen` produces, only relocated:
//! `canon bindgen` was designed for one-shot point-at-a-WIT generation;
//! `canon install` is the flow a user will actually run from inside a
//! project.
//!
//! `bindgen/` is the conventional output directory; it's expected to be
//! gitignored in user projects (the binding files are derivable from
//! the WIT sources under `wit/`, same way `target/` is derivable from
//! Cargo manifests). Compiler-internal packages may commit their
//! `bindgen/` so `cargo build` works on a fresh clone.

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::time::SystemTime;

use crate::bindgen;

/// Name of the sidecar file `canon install` writes alongside the
/// generated bindings. Maps each emitted `.can` file's `bindgen/`-relative
/// path to the WIT interface URN it was generated from.
///
/// The loader derives URNs from paths directly now, so this index is
/// no longer consulted to resolve `extern Wasm` declarations. It
/// remains a derived artifact used only for install staleness
/// detection (`needs_install` below) — regenerated by `canon install`,
/// committed for `canon/std` so `cargo build` works on a fresh clone,
/// gitignored in user projects.
///
/// Format is a tiny TOML subset: one `"<rel>" = "<urn>"` line per
/// file, in alphabetical order. The first two lines are a fixed comment
/// header so anyone opening the file knows it's a derived artifact.
pub const INSTALL_INDEX_FILENAME: &str = "_install.toml";

/// The parsed contents of `bindgen/_install.toml`.
///
/// `entries` keys are `.can` file paths relative to the `bindgen/`
/// directory (e.g. `"wasi/clocks/monotonic_clock.can"`); values are
/// WIT interface URNs of the form `"<ns>:<pkg>/<iface>@<version>"`
/// (without a trailing `#<fn>`).
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct InstallIndex {
    pub entries: BTreeMap<String, String>,
}

/// Parse an `_install.toml` file. The format is intentionally a strict
/// subset of TOML: comment lines starting with `#`, blank lines, and
/// `"key" = "value"` pairs. Anything else is an error.
pub fn parse_install_index(source: &str) -> Result<InstallIndex, String> {
    let mut entries = BTreeMap::new();
    for (idx, raw) in source.lines().enumerate() {
        let line_no = idx + 1;
        let line = raw.split('#').next().unwrap_or("").trim();
        if line.is_empty() {
            continue;
        }
        let eq = line.find('=').ok_or_else(|| {
            format!("{INSTALL_INDEX_FILENAME}:{line_no}: expected `key = value`, got `{line}`")
        })?;
        let key = unquote(line[..eq].trim())
            .map_err(|m| format!("{INSTALL_INDEX_FILENAME}:{line_no}: key: {m}"))?;
        let value = unquote(line[eq + 1..].trim())
            .map_err(|m| format!("{INSTALL_INDEX_FILENAME}:{line_no}: value: {m}"))?;
        if entries.contains_key(&key) {
            return Err(format!(
                "{INSTALL_INDEX_FILENAME}:{line_no}: duplicate entry `{key}`"
            ));
        }
        entries.insert(key, value);
    }
    Ok(InstallIndex { entries })
}

fn unquote(raw: &str) -> Result<String, String> {
    if raw.len() < 2 || !raw.starts_with('"') || !raw.ends_with('"') {
        return Err(format!("expected quoted string, got `{raw}`"));
    }
    let inner = &raw[1..raw.len() - 1];
    if inner.contains('"') || inner.contains('\\') {
        return Err("embedded escapes / quotes not supported".to_string());
    }
    Ok(inner.to_string())
}

/// Top-level install error. Wraps every failure mode (missing WIT,
/// bindgen failure, IO) in one type so the CLI surface has a single
/// error to print.
#[derive(Debug)]
pub struct InstallError(pub String);

impl std::fmt::Display for InstallError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

impl std::error::Error for InstallError {}

/// Outcome of a successful install.
#[derive(Debug)]
pub struct InstallOutcome {
    /// Project-relative paths of every binding file that was written.
    /// Sorted alphabetically.
    pub written: Vec<PathBuf>,
    /// Human-readable lines describing items the install couldn't yet
    /// realize: wasm-component entries (pending composition), interfaces
    /// inside a WIT whose shape the bindgen skips (resources, etc.), and
    /// any other "we noticed this but did nothing" cases. Surfaced to
    /// stderr by the CLI.
    pub skipped: Vec<String>,
}

/// One import source found under `<project>/wit/`.
///
/// The kind is determined by shape: a directory or a `.wit` file is a
/// WIT contract the runtime must satisfy (linker-provided, à la WASI);
/// a `.wasm` file is a component to compose into the final artifact at
/// build time (deferred until composition lands).
#[derive(Debug, Clone, PartialEq, Eq)]
enum WitSource {
    /// A `.wit` file or a directory of `.wit` files.
    Wit(PathBuf),
    /// A wasm component whose exports satisfy the imports.
    Wasm(PathBuf),
}

/// Enumerate the import sources under `wit_root`: every immediate
/// entry, alphabetically. Hidden entries (dotfiles) are skipped;
/// anything that is neither a directory, a `.wit` file, nor a `.wasm`
/// component is an error — the `wit/` directory is a declaration, so
/// stray files in it are a mistake worth naming.
fn wit_sources(wit_root: &Path) -> Result<Vec<WitSource>, InstallError> {
    let entries = fs::read_dir(wit_root)
        .map_err(|e| InstallError(format!("could not read `{}`: {e}", wit_root.display())))?;
    let mut paths: Vec<PathBuf> = entries.flatten().map(|e| e.path()).collect();
    paths.sort();

    let mut sources = Vec::new();
    for path in paths {
        let name = path
            .file_name()
            .and_then(|s| s.to_str())
            .unwrap_or_default();
        if name.starts_with('.') {
            continue;
        }
        if path.is_dir() || name.ends_with(".wit") {
            sources.push(WitSource::Wit(path));
        } else if name.ends_with(".wasm") {
            sources.push(WitSource::Wasm(path));
        } else {
            return Err(InstallError(format!(
                "unexpected entry `{}` under `{}` (expected a `.wit` file, a directory of `.wit` files, or a `.wasm` component)",
                name,
                wit_root.display()
            )));
        }
    }
    Ok(sources)
}

/// Install every WIT source under `<project_root>/wit/`. Returns the
/// list of files written and any deferred items.
pub fn install(project_root: &Path) -> Result<InstallOutcome, InstallError> {
    let wit_root = project_root.join("wit");
    if !wit_root.is_dir() {
        return Err(InstallError(format!(
            "no `wit/` directory at `{}` — external imports are declared by putting WIT sources under `wit/`",
            project_root.display()
        )));
    }
    let sources = wit_sources(&wit_root)?;
    install_sources(project_root, &sources)
}

/// Walk up from `start` looking for the nearest project root — a
/// directory carrying any of the structural project markers: a `src/`
/// tree of `.can` sources, or a `wit/`, `bindgen/`, or `deps/`
/// tree. Returns `None` if the walk reaches the filesystem root
/// without finding one. `start` may be a file or a directory.
///
/// Used by `ensure_installed` to anchor the staleness check; the
/// loader and LSP share the same marker rule (see
/// `loader::find_project_root`).
pub fn find_project_root(start: &Path) -> Option<PathBuf> {
    let mut cur: PathBuf = if start.is_file() {
        start.parent()?.to_path_buf()
    } else {
        start.to_path_buf()
    };
    loop {
        if is_project_root(&cur) {
            return Some(cur);
        }
        cur = cur.parent()?.to_path_buf();
    }
}

/// The structural project-root test: a directory is a project root when
/// it holds a `src/` tree of `.can` sources or any of the conventional
/// project trees (`wit/`, `bindgen/`, `deps/`). Structure is the only
/// marker — no manifest file, and no reserved filename: which `src/`
/// file is the entry point is a question of *shape* (the world-shaped
/// declaration it contains), answered where targets are resolved.
pub fn is_project_root(dir: &Path) -> bool {
    has_can_file(&dir.join("src"))
        || dir.join("wit").is_dir()
        || dir.join("bindgen").is_dir()
        || dir.join("deps").is_dir()
}

/// Whether `dir` directly contains a `.can` file. The `src/`-marker
/// test above and package/workspace discovery in the CLI share it.
pub fn has_can_file(dir: &Path) -> bool {
    std::fs::read_dir(dir)
        .map(|entries| {
            entries.flatten().any(|e| {
                let p = e.path();
                p.is_file() && p.extension().is_some_and(|ext| ext == "can")
            })
        })
        .unwrap_or(false)
}

/// Result of an `ensure_installed` call.
#[derive(Debug)]
pub enum EnsureOutcome {
    /// No project root found, or the project has no `wit/` sources.
    /// Nothing was done; the binding tree (if any) is left as-is.
    NoProject,
    /// `bindgen/` was already in sync with the WIT sources under
    /// `wit/` — no install needed. This is the steady-state path,
    /// so it stays silent.
    UpToDate,
    /// An install was run because the binding tree was missing or
    /// stale. The wrapped `InstallOutcome` lists what was written so
    /// the caller can surface it (e.g. on stderr).
    Installed(InstallOutcome),
}

/// Run `install` on the project containing `start_path` if any of the
/// WIT sources under its `wit/` directory appear out-of-date relative
/// to the materialized `bindgen/_install.toml` index. This is the
/// auto-installer hook the CLI calls from `canon run` / `canon check` /
/// `canon build` / `canon test`, so users don't have to remember a
/// separate step.
///
/// Staleness rules (any of):
///   * `bindgen/_install.toml` doesn't exist (never installed).
///   * `wit/` itself has an mtime newer than the index (a source was
///     added or removed).
///   * Any WIT source under `wit/` has an mtime newer than the index.
///     For directory sources, we take the max mtime over every `.wit`
///     file inside.
///
/// Up-to-date short-circuits fast — no bindgen, no IO into `bindgen/`.
/// The cost on the steady-state path is one directory listing of
/// `wit/` plus a `metadata()` per source.
pub fn ensure_installed(start_path: &Path) -> Result<EnsureOutcome, InstallError> {
    let project_root = match find_project_root(start_path) {
        Some(p) => p,
        None => return Ok(EnsureOutcome::NoProject),
    };

    let wit_root = project_root.join("wit");
    if !wit_root.is_dir() {
        return Ok(EnsureOutcome::NoProject);
    }
    let sources = wit_sources(&wit_root)?;
    if sources.is_empty() {
        return Ok(EnsureOutcome::NoProject);
    }

    if !needs_install(&project_root, &sources, &wit_root) {
        return Ok(EnsureOutcome::UpToDate);
    }

    let outcome = install_sources(&project_root, &sources)?;
    Ok(EnsureOutcome::Installed(outcome))
}

/// Decide whether the materialized bindings are stale relative to the
/// WIT sources under `wit/`. Returns `true` when an install should
/// be run.
fn needs_install(project_root: &Path, sources: &[WitSource], wit_root: &Path) -> bool {
    let bindgen_root = project_root.join("bindgen");
    let index_path = bindgen_root.join(INSTALL_INDEX_FILENAME);

    // No index file yet — install has never been run, or the user
    // deleted `bindgen/`.
    let Ok(index_meta) = fs::metadata(&index_path) else {
        return true;
    };

    // Pre-slice-8 layout: index keys without a versioned package
    // directory (`wasi/clocks/…` instead of `wasi/clocks@0.3.0/…`).
    // The loader only resolves the versioned layout, so an old tree
    // must be regenerated regardless of mtimes.
    if let Ok(src) = fs::read_to_string(&index_path) {
        if let Ok(index) = parse_install_index(&src) {
            let unversioned = |key: &str| {
                key.split('/')
                    .rev()
                    .skip(1) // the file segment carries no version
                    .all(|seg| !seg.contains('@'))
            };
            if index.entries.keys().any(|k| unversioned(k)) {
                return true;
            }
        }
    }
    let Ok(index_mtime) = index_meta.modified() else {
        // Filesystem doesn't expose mtime; conservatively reinstall.
        return true;
    };

    // `wit/` itself changed since the last install (a source was added
    // or removed — a directory's mtime tracks its entry list).
    if mtime_newer_than(wit_root, index_mtime) {
        return true;
    }

    // Any WIT source newer than the index.
    for source in sources {
        let WitSource::Wit(path) = source else {
            continue;
        };
        if max_wit_mtime_newer_than(path, index_mtime) {
            return true;
        }
    }

    false
}

/// True if `path`'s mtime is strictly newer than `cutoff`. Returns
/// false on any IO failure — we prefer false-negatives (skip an
/// install we should have done) only at the cost of slightly stale
/// errors, never false-positives (reinstall unnecessarily, blocking
/// the user).
fn mtime_newer_than(path: &Path, cutoff: SystemTime) -> bool {
    fs::metadata(path)
        .and_then(|m| m.modified())
        .is_ok_and(|t| t > cutoff)
}

/// True if any WIT source under `path` (file or directory) has an
/// mtime newer than `cutoff`.
fn max_wit_mtime_newer_than(path: &Path, cutoff: SystemTime) -> bool {
    if path.is_file() {
        return mtime_newer_than(path, cutoff);
    }
    if path.is_dir() {
        if let Ok(entries) = fs::read_dir(path) {
            for entry in entries.flatten() {
                let p = entry.path();
                if p.extension().and_then(|s| s.to_str()) == Some("wit")
                    && mtime_newer_than(&p, cutoff)
                {
                    return true;
                }
            }
        }
    }
    false
}

/// Same as [`install`], but with an already-enumerated source list.
fn install_sources(
    project_root: &Path,
    sources: &[WitSource],
) -> Result<InstallOutcome, InstallError> {
    let bindgen_root = project_root.join("bindgen");
    let mut written = Vec::new();
    let mut skipped = Vec::new();
    let mut index = InstallIndex::default();

    for source in sources {
        match source {
            WitSource::Wit(wit_path) => {
                let entry_result = install_wit_entry(wit_path, &bindgen_root)?;
                written.extend(entry_result.written);
                skipped.extend(entry_result.skipped);
                for (rel, urn) in entry_result.index_entries {
                    index.entries.insert(rel, urn);
                }
            }
            WitSource::Wasm(path) => {
                skipped.push(format!(
                    "import `{}`: bundled wasm components are not yet supported by `canon install`",
                    path.display()
                ));
            }
        }
    }

    written.sort();

    // Write the install index alongside the generated bindings, but only
    // if anything actually got installed. Skipping the file when there
    // are no entries keeps zero-import projects from having a stray
    // `bindgen/_install.toml`.
    if !index.entries.is_empty() {
        let index_path = bindgen_root.join(INSTALL_INDEX_FILENAME);
        write_install_index(&index_path, &index)?;
        written.push(index_path);
        written.sort();
    }

    Ok(InstallOutcome { written, skipped })
}

/// Result of installing a single `wit/` source. Internal helper —
/// the public outcome flattens these.
struct EntryResult {
    written: Vec<PathBuf>,
    skipped: Vec<String>,
    /// One entry per generated `.can` file: `(rel_path, urn)`. Aggregated
    /// across entries to produce the install index.
    index_entries: Vec<(String, String)>,
}

/// Serialize an `InstallIndex` to disk in the canonical `_install.toml`
/// format. Entries are written alphabetically (BTreeMap iteration order)
/// to keep the file diff-stable across re-runs.
fn write_install_index(path: &Path, index: &InstallIndex) -> Result<(), InstallError> {
    let mut out = String::new();
    out.push_str("# Generated by `canon install`. Do not edit.\n");
    out.push_str(
        "# Each entry maps a `bindgen/`-relative `.can` file to the WIT interface URN it was generated from.\n\n",
    );
    for (rel, urn) in &index.entries {
        out.push_str(&format!("{:?} = {:?}\n", rel, urn));
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .map_err(|e| InstallError(format!("could not create `{}`: {e}", parent.display())))?;
    }
    fs::write(path, out.as_bytes())
        .map_err(|e| InstallError(format!("could not write `{}`: {e}", path.display())))?;
    Ok(())
}

/// Install a single WIT source: parse the WIT (file or directory) and
/// write the generated source under `<bindgen_root>/`.
///
/// The bindgen emits the vendored-package layout directly
/// (`<ns>/<pkg>@<version>/<iface>.can`, see docs/src/spec/modules.md): the
/// directory name carries the pin and the loader derives each
/// binding's URN from the path — the files carry no directive.
fn install_wit_entry(wit_path: &Path, bindgen_root: &Path) -> Result<EntryResult, InstallError> {
    let emitted = bindgen::generate_from_path(wit_path)
        .map_err(|e| InstallError(format!("bindgen failed for `{}`: {e}", wit_path.display())))?;
    if emitted.is_empty() {
        return Err(InstallError(format!(
            "`{}` produced no interfaces",
            wit_path.display()
        )));
    }

    let mut written = Vec::new();
    let mut skipped = Vec::new();
    let mut index_entries = Vec::new();
    for file in emitted {
        // Skip interfaces the bindgen couldn't represent (resources,
        // async-only fns, …) — mirrors the `canon bindgen` CLI behavior.
        if has_no_decls(&file.content) {
            skipped.extend(file.skipped);
            continue;
        }

        let rel = file.relative_path.clone();

        let target = bindgen_root.join(&rel);
        if let Some(parent) = target.parent() {
            fs::create_dir_all(parent).map_err(|e| {
                InstallError(format!("could not create `{}`: {e}", parent.display()))
            })?;
        }

        // Run the emitted source through the canonical formatter, same as
        // `canon bindgen` does. Keeps the on-disk artifact stable across
        // future bindgen whitespace tweaks.
        let content =
            crate::formatter::format(&file.content).unwrap_or_else(|_| file.content.clone());
        fs::write(&target, content.as_bytes())
            .map_err(|e| InstallError(format!("could not write `{}`: {e}", target.display())))?;

        index_entries.push((rel.clone(), file.urn.clone()));
        written.push(target);
        skipped.extend(file.skipped);
    }

    Ok(EntryResult {
        written,
        skipped,
        index_entries,
    })
}

/// Drop the `@<version>` suffix from every path segment:
/// `wasi/clocks@0.3.0/monotonic_clock.can` →
/// `wasi/clocks/monotonic_clock.can`. Used to compare version-carrying
/// vendored paths against version-less package prefixes — source never
/// states versions.
pub(crate) fn strip_version_suffixes(rel: &str) -> String {
    rel.split('/')
        .map(|seg| seg.split_once('@').map(|(l, _)| l).unwrap_or(seg))
        .collect::<Vec<_>>()
        .join("/")
}

/// True when a generated file has no real Canon declarations — only
/// blank lines and `use` directives. Same predicate `canon bindgen`
/// uses when deciding whether to skip writing a file; duplicated here
/// because the bindgen module marks it private. If a future refactor
/// promotes it, we'll switch to that.
pub(crate) fn has_no_decls(content: &str) -> bool {
    content
        .lines()
        .map(|l| l.trim())
        .filter(|l| !l.is_empty())
        .all(|l| l.starts_with("use "))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn strip_version_suffixes_drops_at_segments() {
        assert_eq!(
            strip_version_suffixes("wasi/clocks@0.3.0-rc-2026-03-15/monotonic_clock.can"),
            "wasi/clocks/monotonic_clock.can",
        );
        assert_eq!(
            strip_version_suffixes("wasi/clocks/monotonic_clock.can"),
            "wasi/clocks/monotonic_clock.can",
        );
    }
}
