pub mod ast;
pub mod bindgen;
pub mod checker;
pub mod codegen;
pub mod error;
pub mod formatter;
pub mod install;
pub mod lexer;
pub mod loader;
pub mod lsp;
pub mod monomorph;
pub mod parser;
#[cfg(target_arch = "wasm32")]
pub mod playground;
#[cfg(not(target_arch = "wasm32"))]
pub mod runtime;
pub mod webhost;
