//! The browser side of the web target (docs/src/reference/web-target.md).
//!
//! A web-app program (the `init`/`update`/`view` triple) compiles to a
//! self-contained core module; this module supplies everything around
//! it: the JS host that drives the Elm loop in the browser, the
//! `index.html` shell, a bundle writer for `canon build`, and a tiny
//! static file server for `canon run`.
//!
//! The JS host is deliberately minimal — no virtual DOM, no diffing.
//! `view` returns the whole page as an HTML string and the host swaps
//! it in with `innerHTML` on every update. Events are declarative:
//!
//!   - `data-msg="Increment"` on any element — clicking it sends the
//!     string to `update`.
//!   - `data-msg-form="Add:"` on a `<form>` — submitting sends the
//!     prefix + the first input's value, then clears the input.
//!   - `data-msg-input="SetFilter:"` on an input/select — a `change`
//!     sends the prefix + the current value.
//!   - `data-fetch="URL"` + `data-fetch-msg="Loaded:"` — clicking
//!     GETs the URL and sends prefix + response body. This is the
//!     host-mediated effect that lets a (pure) web app talk to a
//!     Canon backend without any guest-side fetch import.
//!
//! ## Persistence
//!
//! The host can persist app state to `localStorage`. Because a Canon
//! web app's `Model` is a pure fold over messages (`update`), the host
//! never has to serialize the opaque model: it records the *message
//! log* and, on the next load, replays it through `update` to rebuild
//! the exact same model. Enabled by passing a storage key as the third
//! argument to `canonWebStart` — the generated `index.html` keys it by
//! the app's stem, so `canon run`/`canon build` apps persist by
//! default with no guest-side `localStorage` import.

use std::io::{Read, Write};
use std::net::{TcpListener, TcpStream};
use std::path::Path;

/// The JS host, embedded in the compiler binary and written next to
/// the compiled `.wasm` by `canon build` (or served by `canon run`).
pub const CANON_WEB_JS: &str = r#""use strict";
// canon-web.js — generated by `canon build`; do not edit.
// Drives a Canon web app: instantiates the wasm module, holds the
// current model as an opaque value, re-renders on every update.
(function () {
  const STDOUT = "wasi:cli/stdout@0.3.0-rc-2026-03-15";

  // `persistKey` (optional): when a non-empty string, the host records
  // every message in `localStorage[persistKey]` and replays the log on
  // the next load to rebuild the model. See the module docs.
  async function canonWebStart(wasmUrl, root, persistKey) {
    const dec = new TextDecoder();
    const enc = new TextEncoder();
    let exports = null;
    let muteStdout = false;

    // `.print()` in Canon lowers to these five stdout intrinsics;
    // buffer bytes and forward whole lines to the browser console.
    // Muted while replaying the persisted log so a reload does not
    // re-echo every past message.
    let stdoutBuf = "";
    const stdout = {
      "write-via-stream": () => 1,
      "[stream-new-0]write-via-stream": () => (2n << 32n) | 1n,
      "[stream-write-0]write-via-stream": (writer, ptr, len) => {
        stdoutBuf += dec.decode(new Uint8Array(exports.memory.buffer, ptr, len));
        let nl;
        while ((nl = stdoutBuf.indexOf("\n")) >= 0) {
          if (!muteStdout) console.log(stdoutBuf.slice(0, nl));
          stdoutBuf = stdoutBuf.slice(nl + 1);
        }
        return 0;
      },
      "[stream-drop-writable-0]write-via-stream": () => {},
      "[future-drop-readable-1]write-via-stream": () => {},
    };

    const { instance } = await WebAssembly.instantiateStreaming(
      fetch(wasmUrl),
      { [STDOUT]: stdout },
    );
    exports = instance.exports;

    const persist = typeof persistKey === "string" && persistKey.length > 0
      && typeof localStorage !== "undefined";
    let log = [];

    // Apply one message to the current model without persisting or
    // rendering — the shared core of `send` and log replay.
    function apply(model, msg) {
      const bytes = enc.encode(msg);
      const ptr = exports.alloc(bytes.length);
      new Uint8Array(exports.memory.buffer, ptr, bytes.length).set(bytes);
      return exports.update(model, ptr, bytes.length);
    }

    let model = exports.init();

    // Replay the saved message log. A message that no longer folds
    // (e.g. the app's message grammar changed since it was saved)
    // discards the log and starts fresh rather than bricking the app.
    if (persist) {
      try {
        const saved = JSON.parse(localStorage.getItem(persistKey) || "[]");
        if (Array.isArray(saved)) {
          muteStdout = true;
          for (const msg of saved) model = apply(model, String(msg));
          muteStdout = false;
          log = saved.map(String);
        }
      } catch (e) {
        muteStdout = false;
        model = exports.init();
        log = [];
        try { localStorage.removeItem(persistKey); } catch (_) {}
      }
    }

    function render() {
      const [ptr, len] = exports.view(model);
      root.innerHTML = dec.decode(new Uint8Array(exports.memory.buffer, ptr, len));
    }

    function send(msg) {
      model = apply(model, msg);
      if (persist) {
        log.push(msg);
        try { localStorage.setItem(persistKey, JSON.stringify(log)); } catch (_) {}
      }
      render();
    }

    root.addEventListener("click", (e) => {
      const ft = e.target.closest("[data-fetch]");
      if (ft && root.contains(ft)) {
        e.preventDefault();
        fetch(ft.dataset.fetch)
          .then((r) => r.text())
          .then((body) => send((ft.dataset.fetchMsg || "") + body))
          .catch((err) => console.error("canon-web: fetch failed:", err));
        return;
      }
      const t = e.target.closest("[data-msg]");
      if (t && root.contains(t)) {
        e.preventDefault();
        send(t.dataset.msg);
      }
    });
    root.addEventListener("submit", (e) => {
      const form = e.target.closest("[data-msg-form]");
      if (!form) return;
      e.preventDefault();
      const input = form.querySelector("input, textarea, select");
      send(form.dataset.msgForm + (input ? input.value : ""));
      if (input) input.value = "";
    });
    root.addEventListener("change", (e) => {
      const t = e.target;
      if (t.dataset && t.dataset.msgInput !== undefined) {
        send(t.dataset.msgInput + t.value);
      }
    });

    render();
  }

  window.canonWebStart = canonWebStart;
})();
"#;

/// Renders the `index.html` shell for an app whose wasm file is
/// `<stem>.wasm`.
pub fn index_html(stem: &str) -> String {
    format!(
        r#"<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{stem}</title>
</head>
<body>
<div id="app"></div>
<script src="canon-web.js"></script>
<script>canonWebStart("{stem}.wasm", document.getElementById("app"), "canon:{stem}");</script>
</body>
</html>
"#
    )
}

/// Writes the three-file bundle (`<stem>.wasm`, `canon-web.js`,
/// `index.html`) into `dir`. All three are derived artifacts and are
/// overwritten unconditionally.
pub fn write_bundle(dir: &Path, stem: &str, wasm: &[u8]) -> std::io::Result<()> {
    std::fs::create_dir_all(dir)?;
    std::fs::write(dir.join(format!("{stem}.wasm")), wasm)?;
    std::fs::write(dir.join("canon-web.js"), CANON_WEB_JS)?;
    std::fs::write(dir.join("index.html"), index_html(stem))?;
    Ok(())
}

/// Serves the in-memory bundle over HTTP/1.1 until the process exits.
/// Deliberately plain `std::net` + threads — three static files need
/// neither tokio nor hyper, and keeping this synchronous means `canon
/// run` for web apps has no runtime dependency at all.
pub fn serve_bundle(addr: std::net::SocketAddr, stem: &str, wasm: Vec<u8>) -> ! {
    let listener = TcpListener::bind(addr).unwrap_or_else(|e| {
        eprintln!("error: could not bind {addr}: {e}");
        std::process::exit(1);
    });
    eprintln!("canon run: serving web app on http://{addr}");
    let html = index_html(stem);
    let wasm_path = format!("/{stem}.wasm");
    let wasm = std::sync::Arc::new(wasm);
    for stream in listener.incoming() {
        let Ok(stream) = stream else { continue };
        let html = html.clone();
        let wasm_path = wasm_path.clone();
        let wasm = wasm.clone();
        std::thread::spawn(move || {
            let _ = serve_one(stream, &html, &wasm_path, &wasm);
        });
    }
    unreachable!("TcpListener::incoming never returns None")
}

fn serve_one(
    mut stream: TcpStream,
    html: &str,
    wasm_path: &str,
    wasm: &[u8],
) -> std::io::Result<()> {
    // Read up to the end of the request head; the request body (none
    // expected for GETs) is ignored.
    let mut buf = Vec::new();
    let mut chunk = [0u8; 1024];
    while !buf.windows(4).any(|w| w == b"\r\n\r\n") {
        let n = stream.read(&mut chunk)?;
        if n == 0 {
            return Ok(());
        }
        buf.extend_from_slice(&chunk[..n]);
        if buf.len() > 64 * 1024 {
            return Ok(());
        }
    }
    let head = String::from_utf8_lossy(&buf);
    let path = head
        .lines()
        .next()
        .and_then(|line| line.split_whitespace().nth(1))
        .unwrap_or("/");
    let path = path.split('?').next().unwrap_or(path);

    let (status, mime, body): (&str, &str, &[u8]) = if path == "/" || path == "/index.html" {
        ("200 OK", "text/html; charset=utf-8", html.as_bytes())
    } else if path == "/canon-web.js" {
        (
            "200 OK",
            "application/javascript; charset=utf-8",
            CANON_WEB_JS.as_bytes(),
        )
    } else if path == wasm_path {
        ("200 OK", "application/wasm", wasm)
    } else {
        ("404 Not Found", "text/plain; charset=utf-8", b"not found")
    };
    stream.write_all(
        format!(
            "HTTP/1.1 {status}\r\nContent-Type: {mime}\r\nContent-Length: {}\r\nConnection: close\r\n\r\n",
            body.len()
        )
        .as_bytes(),
    )?;
    stream.write_all(body)?;
    Ok(())
}
