Content = Html

Init = Page

Msg = String

Page = String

Page => Content {
    Page -> (
        * "guide" { Guide() -> Html }
        * String { Intro() -> Html }
    )
}

Page => Html {
    <div class="doc">
        {Styles()}
        <nav>
            <button data-msg="Show:intro">Intro</button>
            <button data-msg="Show:guide">Guide</button>
        </nav>
        <hr>
        {Page -> Content}
    </div>
}

Unit => Init {
    Page("intro")
}

Page * Msg => Page {
    Msg -> Substring(From(1) * To(5)) -> (
        * "Show:" { Msg -> Substring(From(6) * Msg -> Length -> To) -> Page }
        * String { Page }
    )
}
